name: deploy-container2

on: 
  push:
    branches:
      - main
    paths:
      - 'packages/container/**'

defaults:
  run:
    working-directory: packages/container

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: InstallNpmAndRun
        id: npm-install-and-run
        run:
          npm install
          npm run build
      
      - name: aws-deploy-pl
        id: aws-deploy-pl
        uses: chrislennon/action-aws-cli@v1.1
      
      - name: aws-deploy
        id: gooi
        env: 
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets:AWS_SECRET_ACCESS_KEY}}
        run: 
          aws s3 sync dist s3://${{secrets.AWS_S3_BUCKET_NAME}}/container/latest